name: Verify PR

on:
  pull_request:
    branches:
      - 'master'

jobs:
  pull_request:
    name: Verify PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
          cache: maven
      - uses: actions/checkout@v2
      - shell: bash
        run: |
          mvn test